#!/usr/bin/env python3
"""
AdwaSport Backend API – Premium Edition
- Category filtering (Football, Basketball, etc.)
- Deep stream metadata (resolution, bitrate, latency)
- Dedicated sport endpoints
- Full backward compatibility
"""

import json
import os
import logging
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import PlainTextResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
import requests

# ---------- Logging ----------
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------- FastAPI App ----------
app = FastAPI(
    title="AdwaSport API",
    description="Premium sports streaming backend with category filters and deep stream validation",
    version="2.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------- Configuration ----------
M3U_URL = "https://raw.githubusercontent.com/henokamdiye/IPTV-Scraper-Zilla/main/adwa_sports.m3u"
CHANNELS_FILE = "channels.json"
MATCHES_FILE = "matches.json"
CATEGORY_FILE = "categorized_streams.json"   # Generated by advanced processor

# ---------- Data Loading ----------
def load_channels() -> Dict[str, Any]:
    if os.path.exists(CHANNELS_FILE):
        try:
            with open(CHANNELS_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Failed to load channels: {e}")
    logger.warning("channels.json not found")
    return {"channels": []}

def load_matches() -> List[Dict]:
    if os.path.exists(MATCHES_FILE):
        try:
            with open(MATCHES_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Failed to load matches: {e}")
    logger.warning("matches.json not found")
    return []

def load_categorized_streams() -> Dict[str, List[Dict]]:
    """Load streams grouped by sport category with deep metadata."""
    if os.path.exists(CATEGORY_FILE):
        try:
            with open(CATEGORY_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Failed to load categorized streams: {e}")
    logger.warning("categorized_streams.json not found")
    return {}

channels_db = load_channels()
matches_db = load_matches()
categorized_db = load_categorized_streams()

logger.info(f"Loaded {len(channels_db.get('channels', []))} channels, {len(matches_db)} matches, {len(categorized_db)} categories")

# ---------- Helper Functions ----------
def get_streams_by_category(category: str) -> List[Dict]:
    """Return streams for a specific category (case-insensitive)."""
    cat_lower = category.lower()
    for cat_name, streams in categorized_db.items():
        if cat_name.lower() == cat_lower:
            return streams
    return []

def filter_streams_by_quality(streams: List[Dict], min_height: int) -> List[Dict]:
    """Keep only streams with resolution height >= min_height."""
    filtered = []
    for s in streams:
        res = s.get("resolution")
        if res and "x" in res:
            try:
                h = int(res.split("x")[1])
                if h >= min_height:
                    filtered.append(s)
            except (ValueError, IndexError):
                continue
    return filtered

# ---------- Root & Health ----------
@app.get("/", tags=["Root"])
async def root():
    return {
        "name": "AdwaSport API",
        "version": "2.0.0",
        "status": "online",
        "channels": len(channels_db.get("channels", [])),
        "matches": len(matches_db),
        "categories": list(categorized_db.keys()),
        "total_streams": sum(len(s) for s in categorized_db.values())
    }

@app.get("/health", tags=["Health"])
async def health():
    return {"status": "healthy", "timestamp": datetime.now(timezone.utc).isoformat()}

# ---------- Live Playlist ----------
@app.get("/live", tags=["Live"])
async def get_live_playlist():
    """Raw M3U playlist of all working sports streams."""
    try:
        resp = requests.get(M3U_URL, timeout=15)
        resp.raise_for_status()
        return PlainTextResponse(content=resp.text, media_type="application/x-mpegURL")
    except Exception as e:
        logger.error(f"Failed to fetch playlist: {e}")
        raise HTTPException(status_code=503, detail=f"Playlist unavailable: {e}")

# ---------- Matches (Existing + Enhanced) ----------
@app.get("/matches", tags=["Matches"])
async def get_matches(limit: Optional[int] = None):
    matches = load_matches()
    if limit:
        matches = matches[:limit]
    return JSONResponse(content=matches)

@app.get("/matches/today", tags=["Matches"])
async def get_today_matches():
    today = datetime.now(timezone.utc).date()
    matches = load_matches()
    today_matches = []
    for m in matches:
        ts = m.get("strTimestamp")
        if ts:
            try:
                match_date = datetime.strptime(ts, "%Y-%m-%dT%H:%M:%S").date()
                if match_date == today:
                    today_matches.append(m)
            except:
                pass
    return today_matches

@app.get("/matches/{match_id}", tags=["Matches"])
async def get_match_details(match_id: str):
    matches = load_matches()
    for m in matches:
        if m.get("idEvent") == match_id:
            return m
    raise HTTPException(status_code=404, detail="Match not found")

@app.get("/matches/{match_id}/streams", tags=["Matches"])
async def get_match_streams(match_id: str):
    """Return available streams for a match using categorized database."""
    matches = load_matches()
    match = next((m for m in matches if m.get("idEvent") == match_id), None)
    if not match:
        raise HTTPException(status_code=404, detail="Match not found")
    
    league = match.get("league_name", "").lower()
    keywords = []
    if "premier" in league:
        keywords = ["premier", "epl", "sky sports", "nbc"]
    elif "champions" in league:
        keywords = ["champions", "ucl", "bt sport", "cbs"]
    elif "la liga" in league:
        keywords = ["la liga", "laliga", "bein", "espn"]
    elif "nba" in league:
        keywords = ["nba", "basketball"]
    else:
        keywords = [league]
    
    candidate_streams = []
    for cat_streams in categorized_db.values():
        for s in cat_streams:
            if any(kw in s["name"].lower() for kw in keywords):
                candidate_streams.append({
                    "id": s.get("id"),
                    "name": s.get("name"),
                    "logo": s.get("logo"),
                    "url": s.get("url"),
                    "quality": s.get("resolution", "HD"),
                    "bitrate": s.get("bitrate"),
                    "latency_ms": s.get("latency_ms")
                })
    
    return {
        "match": match,
        "streams": candidate_streams[:10]
    }

# ---------- Streams & Categories (Premium) ----------
@app.get("/streams", tags=["Streams"])
async def get_all_streams():
    """Legacy endpoint – returns channels.json format."""
    return JSONResponse(content=channels_db)

@app.get("/streams/search", tags=["Streams"])
async def search_streams(q: str = Query(..., min_length=1)):
    """Search channels by name (legacy)."""
    results = [ch for ch in channels_db.get("channels", []) if q.lower() in ch["name"].lower()]
    return results

@app.get("/api/categories", tags=["Premium"])
async def get_categories():
    """List all sport categories with stream counts."""
    return {cat: len(streams) for cat, streams in categorized_db.items()}

@app.get("/api/live-streams", tags=["Premium"])
async def get_live_streams(
    category: Optional[str] = None,
    quality: Optional[str] = None,
    limit: Optional[int] = None
):
    """
    Get live streams with optional category and quality filters.
    - category: e.g., 'football', 'basketball'
    - quality: minimum height, e.g., '720' (for 720p)
    """
    if category:
        streams = get_streams_by_category(category)
        if not streams:
            raise HTTPException(status_code=404, detail=f"Category '{category}' not found")
    else:
        streams = []
        for cat_streams in categorized_db.values():
            streams.extend(cat_streams)
    
    if quality:
        try:
            min_h = int(quality)
            streams = filter_streams_by_quality(streams, min_h)
        except ValueError:
            raise HTTPException(status_code=400, detail="Quality must be an integer (e.g., 720)")
    
    if limit:
        streams = streams[:limit]
    
    return {"streams": streams, "count": len(streams)}

@app.get("/api/football-streams", tags=["Premium"])
async def get_football_streams(quality: Optional[str] = None):
    """Dedicated endpoint for football/soccer streams."""
    streams = get_streams_by_category("football")
    if quality:
        try:
            min_h = int(quality)
            streams = filter_streams_by_quality(streams, min_h)
        except ValueError:
            raise HTTPException(status_code=400, detail="Quality must be an integer")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/basketball-streams", tags=["Premium"])
async def get_basketball_streams():
    streams = get_streams_by_category("basketball")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/american-football-streams", tags=["Premium"])
async def get_american_football_streams():
    streams = get_streams_by_category("american_football")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/baseball-streams", tags=["Premium"])
async def get_baseball_streams():
    streams = get_streams_by_category("baseball")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/hockey-streams", tags=["Premium"])
async def get_hockey_streams():
    streams = get_streams_by_category("hockey")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/motorsport-streams", tags=["Premium"])
async def get_motorsport_streams():
    streams = get_streams_by_category("motorsport")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/combat-streams", tags=["Premium"])
async def get_combat_streams():
    streams = get_streams_by_category("combat")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/cricket-streams", tags=["Premium"])
async def get_cricket_streams():
    streams = get_streams_by_category("cricket")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/tennis-streams", tags=["Premium"])
async def get_tennis_streams():
    streams = get_streams_by_category("tennis")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/golf-streams", tags=["Premium"])
async def get_golf_streams():
    streams = get_streams_by_category("golf")
    return {"streams": streams, "count": len(streams)}

@app.get("/api/stream/{stream_id}", tags=["Premium"])
async def get_stream_details(stream_id: str):
    """Get full details and playable URL for a specific stream."""
    for cat_streams in categorized_db.values():
        for s in cat_streams:
            if s.get("id") == stream_id:
                return s
    raise HTTPException(status_code=404, detail="Stream not found")

@app.get("/api/streams/health/deep", tags=["Admin"])
async def deep_health_check():
    """Placeholder for admin-triggered revalidation."""
    # In production, you'd trigger a background task or webhook
    return {"status": "Deep validation would be triggered here"}

@app.get("/api/matches/with-streams", tags=["Premium"])
async def get_matches_with_streams():
    """Return only matches that have at least one available stream."""
    matches = load_matches()
    result = []
    for m in matches:
        league = m.get("league_name", "").lower()
        keywords = []
        if "premier" in league:
            keywords = ["premier", "epl", "sky", "nbc"]
        elif "champions" in league:
            keywords = ["champions", "ucl"]
        elif "nba" in league:
            keywords = ["nba"]
        else:
            keywords = [league]
        
        available = []
        for s in categorized_db.get("football", []) + categorized_db.get("basketball", []):
            if any(kw in s["name"].lower() for kw in keywords):
                available.append({"id": s.get("id"), "name": s["name"], "url": s["url"]})
        if available:
            m_copy = m.copy()
            m_copy["available_streams"] = available[:3]
            result.append(m_copy)
    return result

# ---------- Channels & Leagues (Legacy/General) ----------
@app.get("/channels", tags=["Channels"])
async def get_channels():
    return JSONResponse(content=channels_db)

@app.get("/leagues", tags=["Leagues"])
async def get_leagues():
    leagues = [
        {"id": "4328", "name": "English Premier League", "country": "England"},
        {"id": "4330", "name": "La Liga", "country": "Spain"},
        {"id": "4332", "name": "Serie A", "country": "Italy"},
        {"id": "4331", "name": "Bundesliga", "country": "Germany"},
        {"id": "4334", "name": "Ligue 1", "country": "France"},
        {"id": "4480", "name": "UEFA Champions League", "country": "Europe"},
        {"id": "4481", "name": "UEFA Europa League", "country": "Europe"},
        {"id": "4387", "name": "NBA", "country": "USA"},
        {"id": "4391", "name": "NFL", "country": "USA"},
        {"id": "4468", "name": "Formula 1", "country": "World"}
    ]
    return leagues

@app.get("/search", tags=["Search"])
async def global_search(q: str = Query(..., min_length=1)):
    q_lower = q.lower()
    results = {"matches": [], "channels": []}
    for m in load_matches():
        if (q_lower in m.get("strEvent", "").lower() or
            q_lower in m.get("strHomeTeam", "").lower() or
            q_lower in m.get("strAwayTeam", "").lower()):
            results["matches"].append(m)
    for ch in channels_db.get("channels", []):
        if q_lower in ch["name"].lower():
            results["channels"].append(ch)
    return results

# ---------- Admin ----------
@app.post("/admin/refresh", tags=["Admin"])
async def refresh_data():
    global channels_db, matches_db, categorized_db
    channels_db = load_channels()
    matches_db = load_matches()
    categorized_db = load_categorized_streams()
    logger.info("Data reloaded via admin endpoint")
    return {
        "status": "refreshed",
        "channels": len(channels_db.get("channels", [])),
        "matches": len(matches_db),
        "categories": len(categorized_db)
    }

# ---------- Run ----------
if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)